### ISSUE TITLE
Tips on how to register helpers

### ISSUE THREAD

**Issue by decosvaldo** [alosaur/handlebars#10]
Dear team, could you please give me some tips on the best and suggested way to register helpers?

On node I was calling a helpers.js file when I was registering all those helpers with Handlebars.registerHelper myself. But I've seen that this implementation is already doing that. So, how should I configure and export them?

Thanks a lot.
Andre

**Comment by irustm** [comment]
you can see it as done in the tests

https://github.com/alosaur/handlebars/blob/master/tests/basic.test.ts
