### ISSUE TITLE
 body htm code does not render

### ISSUE THREAD

**Issue by wilson-pc** [alosaur/handlebars#2]
It does not render the body code in the browser, it shows me the code as it is, when it does log it shows me something like this `& lt; h3 & gt; Alosaur & lt; / h3 & gt; `on the console

**Comment by irustm** [comment]
You must remove the body char escaping. I corrected that in an [example](https://github.com/alosaur/handlebars/blob/master/views/layouts/main.hbs) 


layout/main.hbs

without escaping:
```
{{{ body }}}
```
with 
```
{{ body }}
```

**Comment by wilson-pc** [comment]
Thank you, your answer helped me.
